### ISSUE TITLE
Appendix F is titled Appendix A

### ISSUE THREAD

**Issue by gdfldm** [OPM/opm-reference-manual#165]
How best to change this as I believe it is part of main.fodt?

**Comment by hakonhagland** [comment]
Strange, in the table of contents it is titled F:

![image](https://github.com/OPM/opm-reference-manual/assets/6708379/41ef8409-b7c6-4a86-8a9b-a7605daa8c82)

I will have a look at what is going on here

**Comment by hakonhagland** [comment]
The table of content in Appendix B is also using "A" instead of "B"

**Comment by hakonhagland** [comment]
> The table of content in Appendix B is also using "A" instead of "B":

This is fixed by running "Update index" on the table of content. However, it does not help to run "Update index" on Appendix F. I cannot see, anything special about Appendix F that should prevent it from getting the correct heading number. To debug this further, I think it would be best to extract all remaining appendices (C,D,F) from main.fodt into files. Then, it is easier to leave out appendices from main.fodt and see how it affects the heading numbering. 

I will start extracting the remaining appendices.

**Comment by hakonhagland** [comment]
> Then, it is easier to leave out appendices from main.fodt and see how it affects the heading numbering.

After extracting the remaining appendices, see #166, #167, and #168, I tried to remove Appendix E from main.fodt. Now, Appendix F got the correct heading number (E), so there might be a problem in Appendix E somewhere, that messes up the heading numbering of the appendix after (Appendix F).

**Comment by hakonhagland** [comment]
Found the problem, see #169
